import { motion } from "motion/react";
import { Link } from "react-router-dom";
import { Play, Sparkles, Shield, Heart, ArrowRight, Star } from "lucide-react";

export default function LandingPage() {
  return (
    <div className="relative overflow-hidden">
      {/* Background Gradients */}
      <div className="absolute top-0 left-0 w-full h-full -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-indigo-100/50 rounded-full blur-3xl" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-teal-50/50 rounded-full blur-3xl" />
      </div>

      {/* Navigation */}
      <nav className="max-w-7xl mx-auto px-6 py-8 flex justify-between items-center">
        <div className="flex items-center gap-2">
          <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-200">
            <Sparkles className="text-white w-6 h-6" />
          </div>
          <span className="text-xl font-bold tracking-tight text-slate-900">ZenFlow AI</span>
        </div>
        <div className="flex items-center gap-6">
          <Link to="/auth" className="text-sm font-medium text-slate-600 hover:text-indigo-600 transition-colors">Sign In</Link>
          <Link to="/session/new" className="px-5 py-2.5 bg-indigo-600 text-white rounded-full text-sm font-semibold shadow-md hover:bg-indigo-700 transition-all">
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 pt-20 pb-32 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <span className="inline-block px-4 py-1.5 bg-indigo-50 text-indigo-600 rounded-full text-xs font-bold uppercase tracking-wider mb-6">
            AI-Powered Mindfulness
          </span>
          <h1 className="text-5xl md:text-7xl font-extrabold text-slate-900 tracking-tight leading-[1.1] mb-8">
            Transform Your Mind <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-teal-500">
              In Minutes
            </span>
          </h1>
          <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-600 leading-relaxed mb-12">
            Experience personalized meditation and yoga sessions generated by AI, 
            tailored to your goals, mood, and schedule.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link to="/session/new" className="w-full sm:w-auto px-8 py-4 bg-indigo-600 text-white rounded-2xl text-lg font-bold shadow-xl shadow-indigo-200 hover:bg-indigo-700 hover:-translate-y-1 transition-all flex items-center justify-center gap-2 group">
              Start Your Free Session
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </Link>
            <button className="w-full sm:w-auto px-8 py-4 bg-white text-slate-900 border border-slate-200 rounded-2xl text-lg font-bold hover:bg-slate-50 transition-all flex items-center justify-center gap-2">
              <Play className="w-5 h-5 text-indigo-600" />
              Watch Demo
            </button>
          </div>
        </motion.div>

        {/* Social Proof */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.4, duration: 0.8 }}
          className="mt-24 pt-12 border-t border-slate-100"
        >
          <p className="text-sm font-semibold text-slate-400 uppercase tracking-widest mb-8">Trusted by 50,000+ mindful souls</p>
          <div className="flex flex-wrap justify-center gap-8 md:gap-16 opacity-50 grayscale">
            <div className="font-bold text-2xl text-slate-900 italic">Mindful</div>
            <div className="font-bold text-2xl text-slate-900 italic">YogaLife</div>
            <div className="font-bold text-2xl text-slate-900 italic">ZenDaily</div>
            <div className="font-bold text-2xl text-slate-900 italic">FlowState</div>
          </div>
        </motion.div>
      </section>

      {/* Benefits Section */}
      <section className="bg-white py-32">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-20">
            <h2 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">Designed for Your Well-being</h2>
            <p className="text-slate-600 max-w-xl mx-auto">Our AI understands your needs and creates a unique path to tranquility every time you practice.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { icon: Sparkles, title: "AI-Personalized", desc: "Every session is unique, generated in real-time based on your goals and mood.", color: "bg-indigo-50 text-indigo-600" },
              { icon: Shield, title: "Expert Guidance", desc: "AI models trained on ancient wisdom and modern mindfulness techniques.", color: "bg-teal-50 text-teal-600" },
              { icon: Heart, title: "Holistic Approach", desc: "Combining meditation, breathwork, and yoga for total mind-body harmony.", color: "bg-rose-50 text-rose-600" }
            ].map((benefit, i) => (
              <div key={i} className="p-8 rounded-3xl border border-slate-100 hover:border-indigo-100 hover:shadow-xl hover:shadow-indigo-50/50 transition-all group">
                <div className={`w-14 h-14 ${benefit.color} rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform`}>
                  <benefit.icon className="w-7 h-7" />
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-3">{benefit.title}</h3>
                <p className="text-slate-600 leading-relaxed">{benefit.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-32 bg-indigo-50/30">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid md:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl font-bold text-slate-900 mb-8 leading-tight">What our community says about ZenFlow</h2>
              <div className="space-y-8">
                {[
                  { name: "Sarah J.", role: "Yoga Teacher", text: "The AI-generated flows are surprisingly intuitive. It's like having a personal assistant for my practice." },
                  { name: "David M.", role: "Software Engineer", text: "ZenFlow helped me manage my work stress in just 10 minutes a day. The voice guidance is incredibly soothing." }
                ].map((t, i) => (
                  <div key={i} className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                    <div className="flex gap-1 mb-3">
                      {[1, 2, 3, 4, 5].map(s => <Star key={s} className="w-4 h-4 fill-amber-400 text-amber-400" />)}
                    </div>
                    <p className="text-slate-700 italic mb-4">"{t.text}"</p>
                    <div>
                      <span className="font-bold text-slate-900">{t.name}</span>
                      <span className="text-slate-400 text-sm ml-2">— {t.role}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="relative">
              <div className="aspect-square bg-gradient-to-br from-indigo-200 to-teal-100 rounded-3xl overflow-hidden shadow-2xl">
                <img 
                  src="https://picsum.photos/seed/meditation/800/800" 
                  alt="Meditation" 
                  className="w-full h-full object-cover mix-blend-overlay opacity-80"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="absolute -bottom-8 -left-8 bg-white p-6 rounded-2xl shadow-xl border border-slate-100 max-w-[240px]">
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-3 h-3 bg-green-500 rounded-full animate-pulse" />
                  <span className="text-sm font-bold text-slate-900">Live Session</span>
                </div>
                <p className="text-xs text-slate-500">Join 1,240 others practicing mindfulness right now.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-100 py-12">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
              <Sparkles className="text-white w-5 h-5" />
            </div>
            <span className="text-lg font-bold tracking-tight text-slate-900">ZenFlow AI</span>
          </div>
          <div className="flex gap-8 text-sm font-medium text-slate-500">
            <a href="#" className="hover:text-indigo-600">Privacy</a>
            <a href="#" className="hover:text-indigo-600">Terms</a>
            <a href="#" className="hover:text-indigo-600">Contact</a>
          </div>
          <p className="text-sm text-slate-400">© 2026 ZenFlow AI. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
